#!/usr/bin/env node
/**
 * Reads all .py files in this directory and generates ../py_chunks.ts
 * with each file as a named string export.
 *
 * Run: node src/py/gen_chunks.js
 *
 * File names are converted to camelCase export names:
 *   build_spectrogram.py → buildSpectrogram
 *   spectrogram_mel.py   → spectrogramMel
 */
const fs = require('fs');
const path = require('path');

const pyDir = __dirname;
const outFile = path.join(pyDir, '..', 'py_chunks.ts');

const files = fs.readdirSync(pyDir)
  .filter(f => f.endsWith('.py'))
  .sort();

const toCamel = (name) =>
  name.replace(/\.py$/, '')
    .replace(/_([a-z])/g, (_, c) => c.toUpperCase());

let out = '// Auto-generated by src/py/gen_chunks.js — do not edit.\n';
out += '// Source: src/py/*.py\n\n';

for (const file of files) {
  const content = fs.readFileSync(path.join(pyDir, file), 'utf-8');
  const exportName = toCamel(file);
  // Escape backticks and ${} in the Python code
  const escaped = content.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
  out += `export const ${exportName} = \`${escaped}\`;\n\n`;
}

fs.writeFileSync(outFile, out);
console.log(`Generated ${outFile} with ${files.length} chunks: ${files.join(', ')}`);
