export interface SectionDocs {
  _intro: string;
  [field: string]: string | Record<string, string>;
}

export const DOCS: Record<string, SectionDocs> = {
  project: {
    _intro: `Setup controls project creation, loading, and configuration file paths.\nUse "Create New" to start a fresh project or "Load Existing" to open saved files.`,
    '_sub:Create New': `Enter a project name and click Create. This generates default file paths under annotator_config/ and opens the other sections for editing.`,
    '_sub:Load Existing': `Choose a file type (project, config, or form), browse or type a path, and click Load. Loading cascades: a project file loads its referenced config, which loads its referenced form.`,
    '_sub:Configuration Files': `Controls which files are enabled and where they are saved. Each checkbox enables or disables a file — unchecking inlines its contents into the parent file.\n\n• Linked mode: all three files share the same base name. Editing the linked name updates all paths.\n• Duplicate: unlocks the paths for manual editing. Use this to save a copy under new filenames.\n• Lock: returns to read-only mode.`,
    'project file': `Project-specific configuration — data sources, audio paths, output locations, and anything unique to this particular review task. References the config file for shared app settings.\nLoad: populates all sections and cascades into config and form files if referenced.`,
    'config file': `Application setup shared across multiple projects — layout options, column visibility, capture settings, heights, and general widget behavior. Referenced by the project file; references the form file.\nLoad: populates app/layout sections and cascades into the form file if referenced.`,
    'form file': `Form definition only — the annotation interface controls (selects, textboxes, checkboxes, etc.) and dynamic forms. Kept separate so the same form can be reused across different project/config combinations.\nLoad: populates the form section only.`,
  },
  data: {
    _intro: `Data is where you define your clip source — a table of detections or segments to review. Each row represents one clip. The table must have at minimum a start_time column (or you must map one). Supported formats: CSV, Parquet, JSON, JSONL.`,
    source_type: `How to load the data table.`,
    '_group:source_type': {
      path: `Local file path (CSV, Parquet, JSON, JSONL) relative to the working directory.\nExample: data/detections.csv`,
      url: `Remote file URL. Downloaded and read based on extension or content type.`,
      sql: `DuckDB SQL query. Requires duckdb.\nExample: SELECT * FROM 'data.parquet' WHERE confidence > 0.5`,
      api: `REST API endpoint. Response parsed as JSON.\nExample: https://api.example.com/v1/detections`,
    },
    display_columns: `(optional) Subset of columns shown in the clip table.\nIf empty, all columns are included. Use this to limit what's visible and reduce memory for large files.`,
    start_time_col: `(optional) Column name containing the segment start time in seconds.\nDefault: "start_time". Remap if your file uses a different name.`,
    end_time_col: `(optional) Column name containing the segment end time in seconds.\nDefault: "end_time". Remap if your file uses a different name.`,
    duration: `(optional) Column name or fixed number (seconds) to compute end_time from start_time.\nUse this if your data has duration instead of end_time.\nExample: "duration" (column) or 5.0 (fixed seconds).`,
    secrets: `(optional) Key-value pairs for credentials needed to access data.\nExample: API tokens, database passwords. Stored in the session only, never written to config files.`,
  },
  audio: {
    _intro: `Audio defines where to find the sound files for each clip.\nYou can point to a single file, a URL, or a per-row column that holds the path for each detection.`,
    source_type: `How to resolve the audio file for each clip.`,
    '_group:source_type': {
      path: `Single local audio file shared by all clips.\nExample: recordings/site-a.flac`,
      url: `Remote audio file URL (HTTPS, S3, GCS). Supports partial byte-range downloads.`,
      column: `Per-row audio — each row's value in the selected data column is used as the audio path.\nUse with prefix/suffix/fallback for flexible path resolution.`,
    },
    value: `(required) The file path, URL, or column name depending on source type.\nFor "column" mode, select which data column holds the audio paths.`,
    prefix: `(optional) Prepended to the audio path with "/" separator.\nUseful for base directories or URL roots.\nExample: "audio/" turns "recording.flac" into "audio/recording.flac"`,
    suffix: `(optional) Appended to the audio path.\nUseful for adding file extensions when paths are stored without them.`,
    fallback: `(optional) Fallback audio file used when column mode yields an empty value.`,
    secrets: `(optional) Key-value pairs for credentials needed to access audio.\nExample: storage tokens or signed URL secrets.`,
  },
  output: {
    _intro: `Output controls where annotation results are saved.\nResults are written as a table (CSV/Parquet) with one row per submission. Optionally sync to remote storage.`,
    'output path': `(optional) Output file path for saved annotations.\nAuto-generated from project name if form is configured.\nExample: outputs/reviews.csv`,
    sync_uri: `(optional) Remote URI to sync the output file after writes.\nExample: s3://my-bucket/annotations/reviews.csv`,
    sync_button: `(optional) Show a sync button in the widget.\nSet to true for default "Sync" label, or provide a custom string.`,
    sync_label: `(optional) Text label shown next to the sync button.`,
    recursive: `(optional) Write output after every submission instead of waiting for session end. Default: false.`,
    secrets: `(optional) Key-value pairs for credentials needed for output sync.\nExample: S3 access keys for remote sync.`,
  },
  app: {
    _intro: `Application settings control the widget layout, visible columns, and interaction features like capture and buffering.`,
    project_name: `(optional) Widget header title displayed at the top of the annotator.\nIf not set, it is auto-derived from the project filename.`,
    display_columns: `(optional) Columns visible in the clip table.\nControls which columns appear as sortable table headers.`,
    info_card_title: `(optional) Template string shown prominently in the info card and used for naming captured files.\nSupports [[column_name]] placeholders.\nExample: "[[common_name]]"`,
    info_card_text: `(optional) Template string shown after the time range in the info card.\nSupports [[column_name]] placeholders.\nExample: "species: [[scientific_name]] | confidence: [[confidence]]"`,
    duplicate_entries: `(optional) Allow multiple submissions per row. Default: false.\nEnable for tasks where the same clip needs multiple annotations.`,
    default_buffer: `(optional) Buffer time in seconds added before/after the audio segment.\nDefault: 3. Increase for more context around short clips.`,
    capture: `(optional) Capture button lets users save audio clips.\nSet to false to hide, true for default label, or a string for custom label.`,
    capture_dir: `(optional) Directory where captured audio clips are saved.\nDefault: "captures/"`,
    width: `(optional) Inline widget width. Default: "100%".\nCan be pixels ("800px") or percentage.`,
    clip_table_height: `(optional) Clip table height in pixels. Default: 175.`,
    player_height: `(optional) Player/spectrogram height in pixels. Default: 260.\nAlso determines the spectrogram resolution.`,
    info_card_height: `(optional) Info card height in pixels. Default: 34.`,
    form_panel_height: `(optional) Form panel height in pixels. Default: 140.`,
    capture_height: `(optional) Capture image height in pixels.\nDefaults to player_height if not set.`,
    secrets: `(optional) Global key-value pairs for credentials available to all sections.\nSection-level secrets override global ones with the same key.`,
  },
  description: {
    _intro: `Add an optional collapsible section at the top of the annotator for project descriptions, reviewer instructions, or other guidance. Accepts inline markdown or a path to a markdown file.`,
    title: `(optional) Title shown in the collapsible description bar.\nDefault: "Description".`,
    text: `(optional) Markdown-formatted text displayed in the description panel.\nSupports headings, lists, bold, italic, code blocks, links, and horizontal rules.`,
    description_path: `(optional) Path to a markdown file whose contents populate the description panel.\nOverridden by text if both are set.`,
    open: `(optional) Whether the description panel starts expanded.\nDefault: true.`,
    height: `(optional) Max height in pixels for the description body.\nLeave empty for auto height. Set to constrain long descriptions with scroll.`,
  },
  form: {
    _intro: `Form defines the annotation interface — the controls users interact with to label each clip. Elements are rendered in order. Each element writes its value to a specified output column.\n\nElement types: title, select, textbox, checkbox, number, annotation, pass_value, fixed_value, submission_buttons.`,
    '_sub:Display': `Static elements that show information but do not collect user input.`,
    title: `Display title at the top of the form. Set "value" for the text.\nEnable "progress_tracker" to show completion percentage.`,
    text: `Static text displayed in the form. Set "value" for the text content.`,
    line: `Horizontal rule divider between form elements.`,
    break: `Visual spacer that adds vertical space between form elements.`,
    '_sub:User Input': `Interactive elements that collect user input and write to output columns.`,
    annotation: `Add spectrogram interaction tools for time and frequency selection.`,
    '_group:annotation': {
      time_select: `Single vertical line on the spectrogram. Click to position.\nWrites: start_time.`,
      start_end_time_select: `Two vertical lines — green (start) and pink (end). Lines cannot cross each other. A shaded region appears between them.\nWrites: start_time, end_time.`,
      fixed_duration: `Fixed-length time region centered on click position. Click to place, drag to reposition, arrow keys to nudge.\nConfigure with "window" (fixed) or "initial_window" (user-editable with optional min/max/step bounds).\nWrites: start_time, end_time.`,
      bounding_box: `Click+drag rectangle with individually draggable edges for time and frequency bounds.\nWrites: start_time, end_time, min_frequency, max_frequency.`,
      multibox: `Draw multiple bounding boxes, each with an optional per-box form. One output row per box on submit.\nUse annotation "form" field to reference a dynamic_forms section.\nWrites: start_time, end_time, min_frequency, max_frequency + per-box form values.`,
    },
    select: `Dropdown selector. Requires "label" (display text), "column" (output column name), and "items" (the options). Optional features:\n• required — user must pick a value before submitting\n• filter_box — adds a search input above the dropdown\n• custom_value — lets users type a value not in the list\n• not_available — prepends an N/A option (true for default label, or a custom string)`,
    '_group:select': {
      'add items': `Add options one at a time. Each item has a label (shown in the dropdown), a value (written to output), and an optional form reference that shows/hides a dynamic form section when selected.\nIf only a label is provided, the value defaults to the label text.`,
      'from file': `Load options from a CSV, Parquet, JSON, or JSONL file.\n• value col — column whose values are written to output\n• label col — (optional) column whose values are shown in the dropdown. If omitted, the value column is used for both.\nBrowse or type a path and press Enter to detect columns.`,
      'paste values': `Bulk-add options by pasting text. Choose a separator (comma by default) or check "line delimited" for one item per line.\nAll pasted values are used as both label and value.`,
      range: `Generate numeric options from a min/max/step range.\nExample: min=1, max=5, step=1 produces items 1, 2, 3, 4, 5.`,
    },
    textbox: `Free text input. Set "multiline: true" for a textarea.\nRequires "label" and "column".`,
    checkbox: `Boolean toggle. Optionally set "yes_value" and "no_value" for custom output values (default: true/false).`,
    number: `Numeric input with min/max/step constraints.\nRequires "label", "column", "min", "max", "step".`,
    '_sub:Data': `Elements that write values to the output without user interaction.`,
    pass_value: `Copies a value from the data row into the output.\nSet "source_column" (input) and "column" (output).`,
    fixed_value: `Writes a constant value to the output for every submission.\nSet "column" and "value".`,
    '_sub:Navigation': `Form submission and navigation controls.`,
    submission_buttons: `Submit/skip navigation buttons. Options:\n• line: show a divider above buttons\n• previous: show a back button\n• next: {label: "Skip"} for the skip button\n• submit: {label: "Verify"} for the submit button`,
    dynamic_forms: `Conditional form sections triggered by select item values.\nWhen a select item has "form: section_name", selecting it reveals the named dynamic form section below.`,
  },
};
