export const FIELD_HELP: Record<string, Record<string, string>> = {
  project: {
    project_name: 'Widget header title. Auto-derived from project filename if not set.',
  },
  data: {
    source_type: '(required) How data is loaded: path (local file), url, sql (DuckDB query), or api endpoint.',
    path: '(required) Path to a CSV, Parquet, or JSONL file containing detection rows.',
    start_time_col: 'Column name for segment start time. Default: start_time.',
    end_time_col: 'Column name for segment end time. Default: end_time.',
    duration: 'Column name or fixed number (seconds) to compute end_time from start_time.',
  },
  audio: {
    source_type: '(required) How audio is resolved: path (single file), url, or column (per-row from data).',
    value: '(required) The file path, URL, or column name depending on source type.',
    prefix: 'Prepended to the audio path with /. Useful for relative paths or URLs.',
    suffix: 'Appended to the audio path. Useful for file extensions.',
    fallback: 'Default audio file when column value is empty (column mode only).',
  },
  output: {
    path: 'Output file path. Auto-generated if form is configured. Supports CSV and Parquet.',
    sync_uri: 'Remote endpoint to sync output rows to (POST JSON).',
    sync_button: 'Show a manual sync button. Requires sync_uri.',
    sync_label: 'Custom label for the sync button.',
    recursive: 'Scan output directory recursively for existing submissions.',
  },
  app: {
    info_card_title: 'Template string for info card title. Use [[column_name]] placeholders.',
    info_card_text: 'Template string for info card text. Use [[column_name]] placeholders.',
    display_columns: 'Columns shown in the clip table. Click column chips to add.',
    duplicate_entries: 'Allow multiple submissions per row. Default: false.',
    default_buffer: 'Buffer time in seconds added around segments. Default: 3.',
    capture: "Show capture/screenshot button. False to hide, string for custom label.",
    capture_dir: 'Directory where capture images are saved.',
    width: 'Inline widget width. Default: 100%.',
    clip_table_height: 'Clip table height in pixels. Default: 175.',
    player_height: 'Player/spectrogram height in pixels. Default: 260.',
    info_card_height: 'Info card height in pixels. Default: 34.',
    form_panel_height: 'Form panel height in pixels. Default: 140.',
  },
  form: {
    element_type: '(required) Type of form element: select, textbox, checkbox, number, title, annotation, etc.',
    label: '(required) Display label shown to the user.',
    column: '(required) Output column name where this element\'s value is stored.',
    required: 'Whether the field must be filled before submission.',
    default: 'Default value pre-filled in the field.',
    items: '(required for select) Dropdown options. Inline list, file path, or integer range.',
    filter_box: 'Add a text filter input next to select dropdowns.',
    custom_value: 'Allow user to type a value not in the dropdown list.',
    not_available: "Prepend a fallback 'N/A' option to select items.",
    multiline: 'Use textarea instead of single-line input (textbox only).',
    tools: '(required for annotation) Spectrogram tools: time_select, start_end_time_select, fixed_duration, bounding_box, multibox.',
    start_time: 'Column for annotation start time.',
    end_time: 'Column for annotation end time.',
    min_frequency: 'Column for annotation minimum frequency.',
    max_frequency: 'Column for annotation maximum frequency.',
    dynamic_forms: "Named form sections shown/hidden by select item 'form:' fields.",
  },
};
