export const FIELD_HELP: Record<string, Record<string, string>> = {
  project: {
    project_name: '(optional) Widget header title. Auto-derived from project filename if not set.',
  },
  data: {
    source_type: '(required) How data is loaded: path (local file), url, sql (DuckDB query), or api endpoint.',
    path: '(required) Path to a CSV, Parquet, or JSONL file containing detection rows.',
    start_time_col: '(optional) Column name for segment start time. Default: start_time.',
    end_time_col: '(optional) Column name for segment end time. Default: end_time.',
    duration: '(optional) Column name or fixed number (seconds) to compute end_time from start_time.',
  },
  audio: {
    source_type: '(required) How audio is resolved: path (single file), url, or column (per-row from data).',
    value: '(required) The file path, URL, or column name depending on source type.',
    prefix: '(optional) Prepended to the audio path with /. Useful for relative paths or URLs.',
    suffix: '(optional) Appended to the audio path. Useful for file extensions.',
    fallback: '(optional) Default audio file when column value is empty (column mode only).',
  },
  output: {
    path: '(optional) Output file path. Auto-generated if form is configured. Supports CSV and Parquet.',
    sync_uri: '(optional) Remote endpoint to sync output rows to (POST JSON).',
    sync_button: '(optional) Show a manual sync button. Requires sync_uri.',
    sync_label: '(optional) Custom label for the sync button.',
    recursive: '(optional) Scan output directory recursively for existing submissions.',
  },
  app: {
    info_card_title: '(optional) Template string for info card title. Use [[column_name]] placeholders.',
    info_card_text: '(optional) Template string for info card text. Use [[column_name]] placeholders.',
    display_columns: '(optional) Columns shown in the clip table. Click column chips to add.',
    duplicate_entries: '(optional) Allow multiple submissions per row. Default: false.',
    default_buffer: '(optional) Buffer time in seconds added around segments. Default: 3.',
    capture: "(optional) Show capture/screenshot button. False to hide, string for custom label.",
    capture_dir: '(optional) Directory where capture images are saved.',
    width: '(optional) Inline widget width. Default: 100%.',
    clip_table_height: '(optional) Clip table height in pixels. Default: 175.',
    player_height: '(optional) Player/spectrogram height in pixels. Default: 260.',
    info_card_height: '(optional) Info card height in pixels. Default: 34.',
    form_panel_height: '(optional) Form panel height in pixels. Default: 140.',
  },
  form: {
    element_type: '(required) Type of form element: select, textbox, checkbox, number, title, annotation, etc.',
    label: '(required) Display label shown to the user.',
    column: '(required) Output column name where this element\'s value is stored.',
    required: '(optional) Whether the field must be filled before submission.',
    default: '(optional) Default value pre-filled in the field.',
    items: '(required for select) Dropdown options. Inline list, file path, or integer range.',
    filter_box: '(optional) Add a text filter input next to select dropdowns.',
    custom_value: '(optional) Allow user to type a value not in the dropdown list.',
    not_available: "(optional) Prepend a fallback 'N/A' option to select items.",
    multiline: '(optional) Use textarea instead of single-line input (textbox only).',
    tools: '(required for annotation) Spectrogram tools: time_select, start_end_time_select, fixed_duration, bounding_box, multibox.',
    start_time: '(optional) Column for annotation start time.',
    end_time: '(optional) Column for annotation end time.',
    min_frequency: '(optional) Column for annotation minimum frequency.',
    max_frequency: '(optional) Column for annotation maximum frequency.',
    dynamic_forms: "(optional) Named form sections shown/hidden by select item 'form:' fields.",
  },
};
