audio_column: audio_path
data_columns: ["common_name", "confidence", "start_time", "county", "audio_path"]
prediction_column: common_name
category_path: data/categories-small.csv
capture: false

form_config:
  pass_value:
    source_column: id
    column: detection_id
  is_valid_form:
    - title:
        value: REVIEW
        progress_tracker: true
    - is_valid_select: true
    - textbox:
        label: notes
        column: notes
  no_form:
    - select:
        label: verified name
        column: verified_common_name
        required: true
        items:
          path: data/categories-small.csv
          value: common_name
  submission_buttons:
    line: true
    next:
      label: Skip
    submit:
      label: Verify
