# REVIEW CONFIG
audio: audio_path
data_columns: ["common_name", "confidence", "start_time", "county", "audio_path"]
ident_column: common_name
capture: false

# FORM CONFIG
form_config:
  pass_value:
    source_column: id
    column: detection_id
  title:
    value: REVIEW
    progress_tracker: true
  select:
    label: Is Valid
    column: is_valid
    required: true
    items:
      - label: 'yes'
        value: 'yes'
      - label: 'no'
        value: 'no'
        form: correction_form
  dynamic_forms:
    correction_form:
      - select:
          label: verified name
          column: verified_common_name
          required: true
          items:
            path: data/categories-small.csv
            value: common_name
      - textbox:
          label: notes
          column: notes
  submission_buttons:
    line: true
    next:
      label: Skip
    submit:
      label: Verify
