name: "Test"

on:
  push:
    branches: "main"
  pull_request:
    branches: "*"


concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  unit:
    name: "Run tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd" # v6.0.2
        with:
          persist-credentials: false

      - uses: "prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e"  # v0.9.4

      - name: "Setup"
        env:
          # FIXME: This is not ideal; for immutable install to work correctly
          # we need to commit yarn.lock.
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
        run: "pixi run setup"

      - name: "Test"
        run: "pixi run tests"
